### PR TITLE
Fix font style on Soil case study page

### LINKED ISSUE #408: Font style broken on Soil case study page
soil-case-study-font-style

### PR DESCRIPTION
**Pull request by mark-a-wilson**
Fixes font style on Soil case study page.

Fixes #408

### CODE REVIEW

File: react-frontend/src/components/Nav/covidbanner.js [hunk 1]
```diff
@@ -20,6 +20,7 @@ function CovidBanner(props) {
           <Alert
             style={{
               backgroundColor: '#355992',
+              border: 'none',
```
Comment (thegentlemanphysicist) [inline react-frontend/src/components/Nav/covidbanner.js:23]: I've addressed this in my current PR (I think we both saw it and added the none flag.  I would greatly appreciate deleting this change to prevent merge conflicts.

Comment (mark-a-wilson) [reply react-frontend/src/components/Nav/covidbanner.js:23]: Sure, can you also put in the other commit as well to fix #408? Then we can close this PR.

**Review by thegentlemanphysicist — APPROVED** [review]
sounds good
